### ISSUE TITLE
"UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)"

### ISSUE THREAD

**Issue by madig** [khaledhosny/psautohint#14]
1. Download [Canturell-Regular.zip](https://github.com/khaledhosny/psautohint/files/1150659/Canturell-Regular.zip)
2. `psautohint Canturell-Regular.otf`
```
[...]
Saving font file with new hints...Sat Jul 15 23:51:45 2017
Traceback (most recent call last):
  File "/home/nikolaus/.local/bin/psautohint", line 11, in <module>
    load_entry_point('psautohint==1.1.0.dev0', 'console_scripts', 'psautohint')()
  File "/home/nikolaus/.local/lib/python3.6/site-packages/psautohint/autohint.py", line 1357, in main
    hintFile(options)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/psautohint/autohint.py", line 1324, in hintFile
    fontData.saveChanges()
  File "/home/nikolaus/.local/lib/python3.6/site-packages/psautohint/BezTools.py", line 1206, in saveChanges
    ttFont.save(tempPath)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontTools/ttLib/__init__.py", line 219, in save
    self._writeTable(tag, writer, done)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontTools/ttLib/__init__.py", line 658, in _writeTable
    tabledata = self.getTableData(tag)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontTools/ttLib/__init__.py", line 669, in getTableData
    return self.tables[tag].compile(self)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontTools/ttLib/tables/C_F_F_.py", line 20, in compile
    self.cff.compile(f, otFont)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontTools/cffLib/__init__.py", line 123, in compile
    children = topCompiler.getChildren(strings)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontTools/cffLib/__init__.py", line 431, in getChildren
    children.extend(topDict.getChildren(strings))
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontTools/cffLib/__init__.py", line 2043, in getChildren
    charStringsComp = CharStringsCompiler(items, strings, self)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontTools/cffLib/__init__.py", line 348, in __init__
    self.items = self.getItems(items, strings)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontTools/cffLib/__init__.py", line 507, in getItems
    cs.compile()
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontTools/misc/psCharStrings.py", line 1039, in compile
    bytecode = bytesjoin(bytecode)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontTools/misc/py23.py", line 170, in bytesjoin
    return tobytes(joiner).join(tobytes(item) for item in iterable)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontTools/misc/py23.py", line 170, in <genexpr>
    return tobytes(joiner).join(tobytes(item) for item in iterable)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontTools/misc/py23.py", line 125, in tobytes
    return s.encode(encoding, errors)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
```

Not sure if this is a bug in psautohint or the underlying libs?

**Comment by madig** [comment]
Ah, it's a Python 3 issue. Runs fine with Python 2.

**Comment by khaledhosny** [comment]
Yes, hinting binary fonts does not currently work in Python 3, I need to fix that.
